In [3]:
import torch 
import torch.nn as nn 
import torch.nn.functional as F
import pandas as pd 
import numpy as np
import time 
from tqdm import tqdm

In [4]:
df = pd.read_pickle('data/New folder/train.pkl')
df

          series_id  time_step    close         volume
0                 1          0  0.13700  171985.703125
1                 1          1  0.13656   85451.398438
2                 1          2  0.13647  121151.898438
3                 1          3  0.13693  249110.593750
4                 1          4  0.13715  280344.500000
...             ...        ...      ...            ...
18331219         50     394555  0.37340   54432.101562
18331220         50     394556  0.37360   59362.000000
18331221         50     394557  0.37360   21189.900391
18331222         50     394558  0.37360   36969.500000
18331223         50     394559  0.37330   14054.400391

[18331224 rows x 4 columns]

In [5]:
# -----------------------------
# 1) Simple LSTM Model
# -----------------------------
class LSTMModel(nn.Module):
    def __init__(self, input_size=2, hidden_size=64, num_layers=2, output_size=10, dropout=0.2):
        super().__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, dropout=dropout)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x, hc=None):
        out, (h,c) = self.lstm(x, hc)          # (B, seq_len, hidden)
        out = self.fc(out[:, -1, :])   # use last hidden state
        return out, (h,c)

In [6]:
model = LSTMModel()

print(model)

LSTMModel(
  (lstm): LSTM(2, 64, num_layers=2, batch_first=True, dropout=0.2)
  (fc): Linear(in_features=64, out_features=10, bias=True)
)

IGNORE FROM HERE 
------------------------------

In [4]:
# --------------------------
# 1) Load & sort data
# --------------------------
from tqdm import tqdm
import time

TRAIN_PATH = "train.pkl"
print("reading training data...\n.") 

t0 = time.perf_counter()
train_df = pd.read_pickle(TRAIN_PATH)
train_df = train_df.sort_values(["series_id", "time_step"]).reset_index(drop=True)
t_load = time.perf_counter() - t0
print(f"loaded training data in {t_load:.3f}s")

# Expect columns: series_id, time_step, close, volume

reading training data...
.
loaded training data in 2.115s

In [7]:
new_train_df = pd.DataFrame()

new = train_df.groupby("series_id").agg(mean_close=("close", "mean"),
                                        std_close=("close", "std"),
                                        mean_volume=("volume", "mean"),
                                        std_volume=("volume", "std")).reset_index()

new

    series_id    mean_close    std_close   mean_volume    std_volume
0           1      0.100583     0.029522  6.413277e+04  1.489433e+05
1           2      0.533405     0.148294  8.134202e+03  2.696395e+04
2           3     15.354797     5.510595  1.118376e+03  2.894890e+03
3           4   9173.823242  1569.836182  4.810945e+01  8.013607e+01
4           5      0.746253     0.292024  1.340342e+05  2.176044e+05
5           6      5.217080     1.582593  1.102515e+04  1.922328e+04
6           7     16.192724     7.643600  1.513665e+03  3.952120e+03
7           8      0.348513     0.055784  1.379092e+04  4.359222e+04
8           9      0.081676     0.021421  3.407534e+04  1.126295e+05
9          10      0.790860     0.210102  1.180911e+04  4.353254e+04
10         11      0.052794     0.017299  3.348659e+04  2.000074e+05
11         12      0.197726     0.143840  4.350638e+06  1.274201e+07
12         13      0.792221     0.218219  6.126853e+03  2.205515e+04
13         14      0.127296     0.014531  2.442066e+05  5.086964e+05
14         15      2.607200     1.600691  6.416446e+03  9.768638e+03
15         16      0.007929     0.005525  6.664637e+06  1.632387e+07
16         17      2.258248     0.710544  1.652929e+04  2.861288e+04
17         18      0.071260     0.007761  2.420269e+05  5.839053e+05
18         19      1.988276     1.182441  1.117177e+04  2.596038e+04
19         20      0.001593     0.000374  1.010498e+06  3.964140e+06
20         21      0.052439     0.009812  9.310343e+04  2.374075e+05
21         22      0.579561     0.133097  3.051344e+03  8.511077e+03
22         23     81.160538    29.216223  4.324197e+01  1.312502e+02
23         24      2.053357     0.661639  2.751487e+03  7.088703e+03
24         25      1.694237     0.443676  6.500949e+03  1.687381e+04
25         26      1.936351     0.381713  3.622491e+03  1.375933e+04
26         27      0.074909     0.031780  1.564664e+06  2.637028e+06
27         28      7.860170     4.262455  5.283755e+03  1.059431e+04
28         29      0.483857     0.097897  2.608999e+05  5.195779e+05
29         30      0.023588     0.005244  1.914273e+05  5.654631e+05
30         31      8.523156     4.711914  9.394067e+03  1.520177e+04
31         32  26320.408203  3340.964111  8.450242e+01  1.551731e+02
32         33    290.729248   127.847656  1.260435e+02  2.504217e+02
33         34      0.434114     0.095512  2.735299e+03  7.987349e+03
34         35      0.012073     0.007196  2.091144e+05  5.592352e+05
35         36      2.581236     0.664096  3.061405e+03  9.334445e+03
36         37      0.373588     0.115055  2.226585e+05  4.235648e+05
37         38      0.170354     0.126655  1.777741e+05  3.331148e+05
38         39      0.438050     0.151435  4.057188e+04  1.628798e+05
39         40      0.070465     0.019084  1.100703e+05  2.288436e+05
40         41      0.109146     0.014763  5.390232e+04  1.584250e+05
41         42     31.903854    11.188046  7.763480e+01  2.349381e+02
42         43      1.380660     0.304395  4.232220e+03  1.262793e+04
43         44      0.073076     0.035844  2.487812e+05  4.860481e+05
44         45      4.189503     2.005059  6.512111e+03  1.435173e+04
45         46      0.370632     0.209647  1.157790e+04  3.788253e+04
46         47      0.074141     0.009136  6.983209e+05  1.975678e+06
47         48      0.103289     0.037739  7.489099e+05  1.780561e+06
48         49      0.222374     0.040865  1.354846e+05  2.392188e+05
49         50      0.476090     0.111341  8.606773e+04  1.818660e+05

In [8]:
new = new[~new['series_id'].isin([4,23,32,33,42])]

new

    series_id  mean_close  std_close   mean_volume    std_volume
0           1    0.100583   0.029522  6.413277e+04  1.489433e+05
1           2    0.533405   0.148294  8.134202e+03  2.696395e+04
2           3   15.354797   5.510595  1.118376e+03  2.894890e+03
4           5    0.746253   0.292024  1.340342e+05  2.176044e+05
5           6    5.217080   1.582593  1.102515e+04  1.922328e+04
6           7   16.192724   7.643600  1.513665e+03  3.952120e+03
7           8    0.348513   0.055784  1.379092e+04  4.359222e+04
8           9    0.081676   0.021421  3.407534e+04  1.126295e+05
9          10    0.790860   0.210102  1.180911e+04  4.353254e+04
10         11    0.052794   0.017299  3.348659e+04  2.000074e+05
11         12    0.197726   0.143840  4.350638e+06  1.274201e+07
12         13    0.792221   0.218219  6.126853e+03  2.205515e+04
13         14    0.127296   0.014531  2.442066e+05  5.086964e+05
14         15    2.607200   1.600691  6.416446e+03  9.768638e+03
15         16    0.007929   0.005525  6.664637e+06  1.632387e+07
16         17    2.258248   0.710544  1.652929e+04  2.861288e+04
17         18    0.071260   0.007761  2.420269e+05  5.839053e+05
18         19    1.988276   1.182441  1.117177e+04  2.596038e+04
19         20    0.001593   0.000374  1.010498e+06  3.964140e+06
20         21    0.052439   0.009812  9.310343e+04  2.374075e+05
21         22    0.579561   0.133097  3.051344e+03  8.511077e+03
23         24    2.053357   0.661639  2.751487e+03  7.088703e+03
24         25    1.694237   0.443676  6.500949e+03  1.687381e+04
25         26    1.936351   0.381713  3.622491e+03  1.375933e+04
26         27    0.074909   0.031780  1.564664e+06  2.637028e+06
27         28    7.860170   4.262455  5.283755e+03  1.059431e+04
28         29    0.483857   0.097897  2.608999e+05  5.195779e+05
29         30    0.023588   0.005244  1.914273e+05  5.654631e+05
30         31    8.523156   4.711914  9.394067e+03  1.520177e+04
33         34    0.434114   0.095512  2.735299e+03  7.987349e+03
34         35    0.012073   0.007196  2.091144e+05  5.592352e+05
35         36    2.581236   0.664096  3.061405e+03  9.334445e+03
36         37    0.373588   0.115055  2.226585e+05  4.235648e+05
37         38    0.170354   0.126655  1.777741e+05  3.331148e+05
38         39    0.438050   0.151435  4.057188e+04  1.628798e+05
39         40    0.070465   0.019084  1.100703e+05  2.288436e+05
40         41    0.109146   0.014763  5.390232e+04  1.584250e+05
42         43    1.380660   0.304395  4.232220e+03  1.262793e+04
43         44    0.073076   0.035844  2.487812e+05  4.860481e+05
44         45    4.189503   2.005059  6.512111e+03  1.435173e+04
45         46    0.370632   0.209647  1.157790e+04  3.788253e+04
46         47    0.074141   0.009136  6.983209e+05  1.975678e+06
47         48    0.103289   0.037739  7.489099e+05  1.780561e+06
48         49    0.222374   0.040865  1.354846e+05  2.392188e+05
49         50    0.476090   0.111341  8.606773e+04  1.818660e+05

In [9]:
train_df = train_df[~train_df['series_id'].isin([4,23,32,33,42])]

train_df

          series_id  time_step    close         volume
0                 1          0  0.13700  171985.703125
1                 1          1  0.13656   85451.398438
2                 1          2  0.13647  121151.898438
3                 1          3  0.13693  249110.593750
4                 1          4  0.13715  280344.500000
...             ...        ...      ...            ...
18331219         50     394555  0.37340   54432.101562
18331220         50     394556  0.37360   59362.000000
18331221         50     394557  0.37360   21189.900391
18331222         50     394558  0.37360   36969.500000
18331223         50     394559  0.37330   14054.400391

[16363279 rows x 4 columns]

In [10]:
train_df['volume'].iloc[0:10]

0    171985.703125
1     85451.398438
2    121151.898438
3    249110.593750
4    280344.500000
5    291702.093750
6    108030.000000
7    149102.906250
8     31606.500000
9    168079.593750
Name: volume, dtype: float32

In [13]:
np.log1p(train_df['volume'].iloc[0:10])

0    12.055173
1    11.355715
2    11.704808
3    12.425656
4    12.543778
5    12.583491
6    11.590174
7    11.912398
8    10.361150
9    12.032199
Name: volume, dtype: float32

START FROM HERE 
---------------------

In [ ]:
import pandas as pd

# --------------------------------------------------
# 1) Load the raw training data
# --------------------------------------------------
df = pd.read_pickle("data/New folder/train.pkl")   # original dataset

# --------------------------------------------------
# 2) Drop inconsistent / high-variance series
# --------------------------------------------------
bad_series = [4, 23, 32, 33, 42]
df = df[~df['series_id'].isin(bad_series)].reset_index(drop=True)

# --------------------------------------------------
# 3) Sort by series_id and time_step for consistency
# --------------------------------------------------
df = df.sort_values(['series_id', 'time_step']).reset_index(drop=True)

# --------------------------------------------------
# 4) Split by series_id (80% train / 20% validation)
# --------------------------------------------------
unique_series = sorted(df['series_id'].unique())
n_train = int(0.8 * len(unique_series))

train_ids = unique_series[:n_train]
val_ids   = unique_series[n_train:]

train_df = df[df['series_id'].isin(train_ids)].reset_index(drop=True)
val_df   = df[df['series_id'].isin(val_ids)].reset_index(drop=True)

# --------------------------------------------------
# 5) Save the processed data
# --------------------------------------------------
train_df.to_pickle("data/train_split_train.pkl")
val_df.to_pickle("data/train_split_val.pkl")

In [8]:
from torch.utils.data import IterableDataset
import torch
import numpy as np
from dataset import TrainWindowSampler

class WindowsDataset(IterableDataset):
    """
    Stream overlapping time-series windows per series_id.
    - stride = 5 (overlapping windows)
    - close: kept as-is
    - volume: log1p transformed only
    - no min–max or any other normalization

    Each sample:
        X: (60, 2) float32 -> [close_ratio, log1p(volume)]
        y: (10,)  float32  -> next 10 close ratios
    """

    def __init__(self, train_path: str, step_size: int = 5, seed: int = 1337):
        self.train_path = train_path
        self.step_size = step_size
        self.seed = seed

    def __iter__(self):
        sampler = TrainWindowSampler(
            train_path=self.train_path,
            window=70,
            input_len=60,
            horizon_len=10,
            rolling=True,
            step_size=self.step_size,
            seed=self.seed,
        )

        for X, y in sampler.iter_windows():
            # X: (60,2) -> [close, volume]
            # y: (10,)  -> next 10 closes

            close = X[:, 0].astype(np.float32)                # leave unchanged
            vol   = np.log1p(np.clip(X[:, 1], 0, None)).astype(np.float32)

            X_out = np.stack([close, vol], axis=1)
            y_out = y.astype(np.float32)

            yield torch.from_numpy(X_out), torch.from_numpy(y_out)

In [9]:
from torch.utils.data import DataLoader

train_ds = WindowsDataset(
    train_path="data/train_split_train.pkl", 
    step_size=5,
    seed=1337
)

val_ds = WindowsDataset(
    train_path="data/train_split_val.pkl",    
    step_size=5,
    seed=1337
)

train_loader = DataLoader(train_ds, batch_size=256, num_workers=0)
val_loader   = DataLoader(val_ds, batch_size=256, num_workers=0)

In [10]:
device = "cuda"

In [11]:
# --------------------------
# 4) Model, loss, optim
# --------------------------
print("building model...\n.")
t0 = time.perf_counter()
model = LSTMModel().to(device)
opt = torch.optim.AdamW(model.parameters(), lr=0.0001, weight_decay=1e-4)
crit = nn.MSELoss()
t_model_build = time.perf_counter() - t0
print(f"model built in {t_model_build:.3f}s")

building model...
.
model built in 1.281s

In [12]:
EPOCHS = 10
model.train()
for epoch in range(1, EPOCHS + 1):
    total_loss = 0.0
    total_samples = 0
    pbar = tqdm(train_loader, desc=f"Epoch {epoch}/{EPOCHS}", ncols=100)
    for xb, yb in pbar:
        xb, yb = xb.to(device), yb.to(device)
        opt.zero_grad()
        loss = crit(model(xb), yb)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        opt.step()
        total_loss += loss.item() * xb.size(0)
        total_samples += xb.size(0)
        pbar.set_postfix(loss=f"{total_loss / total_samples:.6f}")
    print(f"Epoch {epoch}: train_mse={total_loss / total_samples:.6f}")

Epoch 1/10: 0it [00:01, ?it/s]

AttributeError: 'tuple' object has no attribute 'size'